const { randomUUID } = require("crypto");
const { StudioValidationError } = require("./validation");

const JOB_TYPES = new Set(["generate-document", "external-video", "render", "media"]);
const JOB_STATUSES = new Set(["queued", "blocked", "running", "cancelled", "completed", "failed"]);
function json(value) { return value == null ? null : JSON.parse(value); }
function mapJob(row) { if (!row) return null; return { id: row.id, projectId: row.project_id, accountId: row.account_id, type: row.type, status: row.status, dedupeKey: row.dedupe_key, input: json(row.input_json), result: json(row.result_json), error: json(row.error_json), progressCurrent: row.progress_current, progressTotal: row.progress_total, attempts: row.attempts, maxAttempts: row.max_attempts, scheduledAt: row.scheduled_at, leaseOwner: row.lease_owner, leaseExpiresAt: row.lease_expires_at, heartbeatAt: row.heartbeat_at, createdAt: row.created_at, updatedAt: row.updated_at, finishedAt: row.finished_at }; }
function id(value, label) { const result = String(value || ""); if (!/^[0-9a-f-]{36}$/i.test(result)) throw new StudioValidationError(`Invalid ${label}.`); return result; }

class JobService {
  constructor({ database, projectService }) { this.db = database.db; this.projectService = projectService; }
  list(accountId, projectId, options = {}) {
    this.projectService.get(accountId, projectId); const status = options.status ? String(options.status) : null;
    if (status && !JOB_STATUSES.has(status)) throw new StudioValidationError("Unsupported job status.");
    return this.db.prepare(`SELECT * FROM studio_jobs WHERE account_id=? AND project_id=? ${status ? "AND status=?" : ""} ORDER BY created_at DESC LIMIT 500`).all(...(status ? [accountId, projectId, status] : [accountId, projectId])).map(mapJob);
  }
  get(accountId, projectId, jobId) { this.projectService.get(accountId, projectId); const row = this.db.prepare("SELECT * FROM studio_jobs WHERE id=? AND account_id=? AND project_id=?").get(jobId, accountId, projectId); if (!row) throw new StudioValidationError("Job not found.", 404); return mapJob(row); }
  enqueue(accountId, projectId, input = {}) {
    this.projectService.get(accountId, projectId); const type = String(input.type || ""); if (!JOB_TYPES.has(type)) throw new StudioValidationError("Unsupported job type.");
    const maxAttempts = input.maxAttempts === undefined ? 1 : Number(input.maxAttempts); if (!Number.isInteger(maxAttempts) || maxAttempts < 1 || maxAttempts > 10) throw new StudioValidationError("Max attempts must be between 1 and 10.");
    const dedupeKey = input.dedupeKey == null ? null : String(input.dedupeKey).trim(); if (dedupeKey && (dedupeKey.length > 200 || !/^[A-Za-z0-9_.:-]+$/.test(dedupeKey))) throw new StudioValidationError("Invalid dedupe key.");
    if (dedupeKey) { const existing = this.db.prepare("SELECT * FROM studio_jobs WHERE account_id=? AND dedupe_key=?").get(accountId, dedupeKey); if (existing) return mapJob(existing); }
    const dependencies = Array.isArray(input.dependsOn) ? [...new Set(input.dependsOn.map((v) => id(v, "dependency identifier")))] : [];
    const scheduled = input.scheduledAt ? new Date(input.scheduledAt) : new Date(); if (!Number.isFinite(scheduled.getTime())) throw new StudioValidationError("Invalid scheduledAt.");
    const payload = input.input ?? {}; let encoded; try { encoded = JSON.stringify(payload); } catch { throw new StudioValidationError("Job input must be JSON."); } if (Buffer.byteLength(encoded) > 1024 * 1024) throw new StudioValidationError("Job input exceeds 1 MB.");
    const jobId = randomUUID(), now = new Date().toISOString(), status = input.status === "blocked" ? "blocked" : "queued";
    this.db.transaction(() => {
      for (const dependency of dependencies) { const row = this.db.prepare("SELECT 1 FROM studio_jobs WHERE id=? AND account_id=? AND project_id=?").get(dependency, accountId, projectId); if (!row) throw new StudioValidationError("Job dependency not found.", 404); }
      this.db.prepare("INSERT INTO studio_jobs (id,project_id,account_id,type,status,dedupe_key,input_json,max_attempts,scheduled_at,created_at,updated_at) VALUES (?,?,?,?,?,?,?,?,?,?,?)").run(jobId, projectId, accountId, type, status, dedupeKey, encoded, maxAttempts, scheduled.toISOString(), now, now);
      for (const dependency of dependencies) this.db.prepare("INSERT INTO studio_job_dependencies(job_id,depends_on_job_id) VALUES (?,?)").run(jobId, dependency);
      this.projectService.recordEvent(accountId, projectId, "job.enqueued", { jobId, type, status }, now);
    })(); return this.get(accountId, projectId, jobId);
  }
  cancel(accountId, projectId, jobId) { const job = this.get(accountId, projectId, jobId); if (!["queued", "blocked", "running", "failed"].includes(job.status)) throw new StudioValidationError("Job cannot be cancelled in its current status.", 409); const now = new Date().toISOString(); this.db.prepare("UPDATE studio_jobs SET status='cancelled',updated_at=?,finished_at=?,lease_owner=NULL,lease_expires_at=NULL WHERE id=? AND account_id=?").run(now, now, jobId, accountId); return this.get(accountId, projectId, jobId); }
  retry(accountId, projectId, jobId) { const job = this.get(accountId, projectId, jobId); if (!["failed", "cancelled", "blocked"].includes(job.status)) throw new StudioValidationError("Only failed, cancelled, or blocked jobs can be retried.", 409); const now = new Date().toISOString(); this.db.prepare("UPDATE studio_jobs SET status='queued',error_json=NULL,result_json=NULL,scheduled_at=?,updated_at=?,finished_at=NULL,lease_owner=NULL,lease_expires_at=NULL WHERE id=?").run(now, now, jobId); return this.get(accountId, projectId, jobId); }
  claim(workerId, options = {}) {
    const worker = String(workerId || "").trim(); if (!worker || worker.length > 100) throw new StudioValidationError("Worker identifier is required."); const type = options.type ? String(options.type) : null; if (type && !JOB_TYPES.has(type)) throw new StudioValidationError("Unsupported job type.");
    const leaseMs = Math.max(5000, Math.min(300000, Number(options.leaseMs) || 30000)); const now = new Date(), expires = new Date(now.getTime() + leaseMs).toISOString(); let claimed = null;
    this.db.transaction(() => { const row = this.db.prepare(`SELECT j.id FROM studio_jobs j WHERE j.status='queued' AND j.scheduled_at<=? ${type ? "AND j.type=?" : ""} AND NOT EXISTS (SELECT 1 FROM studio_job_dependencies d JOIN studio_jobs p ON p.id=d.depends_on_job_id WHERE d.job_id=j.id AND p.status<>'completed') ORDER BY j.scheduled_at,j.created_at LIMIT 1`).get(...(type ? [now.toISOString(), type] : [now.toISOString()])); if (!row) return; const changed = this.db.prepare("UPDATE studio_jobs SET status='running',attempts=attempts+1,lease_owner=?,lease_expires_at=?,heartbeat_at=?,updated_at=? WHERE id=? AND status='queued'").run(worker, expires, now.toISOString(), now.toISOString(), row.id); if (changed.changes) claimed = mapJob(this.db.prepare("SELECT * FROM studio_jobs WHERE id=?").get(row.id)); })(); return claimed;
  }
  heartbeat(jobId, workerId, progress = {}) { const current = Number(progress.current ?? 0), total = Number(progress.total ?? 0); if (!Number.isInteger(current) || !Number.isInteger(total) || current < 0 || total < 0) throw new StudioValidationError("Invalid job progress."); const now = new Date(), expires = new Date(now.getTime() + Math.max(5000, Number(progress.leaseMs) || 30000)).toISOString(); const result = this.db.prepare("UPDATE studio_jobs SET heartbeat_at=?,lease_expires_at=?,progress_current=?,progress_total=?,updated_at=? WHERE id=? AND status='running' AND lease_owner=?").run(now.toISOString(), expires, current, total, now.toISOString(), jobId, workerId); if (!result.changes) throw new StudioValidationError("Running job lease not found.", 409); return mapJob(this.db.prepare("SELECT * FROM studio_jobs WHERE id=?").get(jobId)); }
  finish(jobId, workerId, status, payload) { if (!["completed", "failed"].includes(status)) throw new StudioValidationError("Invalid terminal job status."); const now = new Date().toISOString(), field = status === "completed" ? "result_json" : "error_json"; const result = this.db.prepare(`UPDATE studio_jobs SET status=?,${field}=?,updated_at=?,finished_at=?,lease_owner=NULL,lease_expires_at=NULL WHERE id=? AND status='running' AND lease_owner=?`).run(status, JSON.stringify(payload || {}), now, now, jobId, workerId); if (!result.changes) throw new StudioValidationError("Running job lease not found.", 409); return mapJob(this.db.prepare("SELECT * FROM studio_jobs WHERE id=?").get(jobId)); }
  complete(jobId, workerId, result) { return this.finish(jobId, workerId, "completed", result); }
  fail(jobId, workerId, error) { return this.finish(jobId, workerId, "failed", typeof error === "object" ? error : { message: String(error) }); }
  recoverExpired(nowValue = new Date(), options = {}) { const now = new Date(nowValue); if (!Number.isFinite(now.getTime())) throw new StudioValidationError("Invalid recovery time."); const type = options.type ? String(options.type) : null; if (type && !JOB_TYPES.has(type)) throw new StudioValidationError("Unsupported job type."); return this.db.prepare(`UPDATE studio_jobs SET status=CASE WHEN attempts<max_attempts THEN 'queued' ELSE 'failed' END,error_json=CASE WHEN attempts<max_attempts THEN error_json ELSE json_object('code','lease_expired','message','Worker lease expired.') END,lease_owner=NULL,lease_expires_at=NULL,updated_at=?,finished_at=CASE WHEN attempts<max_attempts THEN NULL ELSE ? END WHERE status='running' AND lease_expires_at<? ${type ? "AND type=?" : ""}`).run(...(type ? [now.toISOString(), now.toISOString(), now.toISOString(), type] : [now.toISOString(), now.toISOString(), now.toISOString()])).changes; }
}
module.exports = { JobService, mapJob, JOB_TYPES, JOB_STATUSES };
