const express = require("express");
const { getStorageStatus } = require("./storage");
const { StudioValidationError } = require("./validation");
const { MAX_ASSET_BYTES, MAX_UPLOAD_CHUNK_BYTES } = require("./asset-service");

function createStudioRouter(services) {
  const { projectService, documentService, timelineService, jobService, mediaService, providerService, assetService, renderService, publicationService, eventHub, rootPath, getActiveAccount, requireAccount } = services;
  const router = express.Router();
  async function requestAccount(req, options = {}) { const requestedId = String(req.get("x-autosocial-account-id") || req.query.accountId || "").trim(); if (requestedId) return requireAccount(requestedId); if (options.allowActive) { const account = await getActiveAccount(); return requireAccount(account.id); } throw new StudioValidationError("An explicit Studio account is required."); }
  const route = (handler) => async (req, res, next) => { try { await handler(req, res); } catch (error) { next(error); } };

  router.get("/health", route(async (req, res) => { const account = await requestAccount(req, { allowActive: true }); const provider = await providerService.health(account.id); res.json({ ok: true, account, storage: await getStorageStatus(rootPath), limits: { maxDurationSeconds: 3600, aspectRatios: ["16:9", "9:16"], maxWidth: 3840, maxHeight: 3840, maxAssetBytes: MAX_ASSET_BYTES, zeroBudgetMode: true }, ...provider }); }));
  router.get("/projects", route(async (req, res) => { const account = await requestAccount(req); res.json({ ok: true, account, projects: projectService.list(account.id, { includeArchived: req.query.includeArchived === "true" }) }); }));
  router.post("/projects", route(async (req, res) => { const account = await requestAccount(req); res.status(201).json({ ok: true, project: await projectService.create(account.id, req.body || {}) }); }));
  router.get("/projects/:projectId", route(async (req, res) => { const account = await requestAccount(req); res.json({ ok: true, project: projectService.get(account.id, req.params.projectId) }); }));
  router.patch("/projects/:projectId", route(async (req, res) => { const account = await requestAccount(req); res.json({ ok: true, project: projectService.update(account.id, req.params.projectId, req.body || {}) }); }));
  router.delete("/projects/:projectId", route(async (req, res) => { const account = await requestAccount(req); res.json({ ok: true, result: projectService.archive(account.id, req.params.projectId, req.body?.baseRevision) }); }));

  router.get("/projects/:projectId/documents/:kind", route(async (req, res) => { const account = await requestAccount(req); const documents = documentService.list(account.id, req.params.projectId, req.params.kind); res.json({ ok: true, documents, document: req.query.version ? documentService.get(account.id, req.params.projectId, req.params.kind, req.query.version) : documents[0] || null }); }));
  router.post("/projects/:projectId/documents/:kind", route(async (req, res) => { const account = await requestAccount(req); res.status(201).json({ ok: true, ...documentService.create(account.id, req.params.projectId, req.params.kind, req.body || {}) }); }));
  router.get("/projects/:projectId/documents/:kind/:version", route(async (req, res) => { const account = await requestAccount(req); res.json({ ok: true, document: documentService.get(account.id, req.params.projectId, req.params.kind, req.params.version) }); }));
  router.post("/projects/:projectId/documents/:kind/:version/approve", route(async (req, res) => { const account = await requestAccount(req); res.json({ ok: true, ...documentService.approve(account.id, req.params.projectId, req.params.kind, req.params.version, req.body || {}) }); }));
  router.post("/projects/:projectId/documents/:kind/:version/restore", route(async (req, res) => { const account = await requestAccount(req); res.status(201).json({ ok: true, ...documentService.restore(account.id, req.params.projectId, req.params.kind, req.params.version, req.body || {}) }); }));
  router.get("/projects/:projectId/timeline", route(async (req, res) => { const account = await requestAccount(req); const documents = documentService.list(account.id, req.params.projectId, "timeline"); res.json({ ok: true, timelines: documents, timeline: documents[0] || null }); }));
  router.post("/projects/:projectId/timeline", route(async (req, res) => { const account = await requestAccount(req); res.status(201).json({ ok: true, ...documentService.create(account.id, req.params.projectId, "timeline", req.body || {}) }); }));
  router.post("/projects/:projectId/rough-cut", route(async (req, res) => { const account = await requestAccount(req); res.status(201).json({ ok: true, ...timelineService.createRoughCut(account.id, req.params.projectId, req.body || {}) }); }));
  router.post("/projects/:projectId/generate", route(async (req, res) => { const account = await requestAccount(req); res.status(201).json({ ok: true, ...(await providerService.generate(account.id, req.params.projectId, req.body || {})) }); }));

  router.get("/projects/:projectId/jobs", route(async (req, res) => { const account = await requestAccount(req); res.json({ ok: true, jobs: jobService.list(account.id, req.params.projectId, req.query) }); }));
  router.post("/projects/:projectId/jobs", route(async (req, res) => { const account = await requestAccount(req); const job = jobService.enqueue(account.id, req.params.projectId, req.body || {}); res.status(201).json({ ok: true, job }); }));
  router.post("/projects/:projectId/media-jobs", route(async (req, res) => { const account = await requestAccount(req); res.status(202).json({ ok: true, job: mediaService.enqueue(account.id, req.params.projectId, req.body || {}) }); }));
  router.get("/projects/:projectId/jobs/:jobId", route(async (req, res) => { const account = await requestAccount(req); res.json({ ok: true, job: jobService.get(account.id, req.params.projectId, req.params.jobId) }); }));
  router.post("/projects/:projectId/jobs/:jobId/cancel", route(async (req, res) => { const account = await requestAccount(req); res.json({ ok: true, job: jobService.cancel(account.id, req.params.projectId, req.params.jobId) }); }));
  router.post("/projects/:projectId/jobs/:jobId/retry", route(async (req, res) => { const account = await requestAccount(req); res.json({ ok: true, job: jobService.retry(account.id, req.params.projectId, req.params.jobId) }); }));

  router.get("/projects/:projectId/assets", route(async (req, res) => { const account = await requestAccount(req); res.json({ ok: true, assets: assetService.list(account.id, req.params.projectId) }); }));
  router.post("/projects/:projectId/uploads/:uploadId/chunks", express.raw({ type: () => true, limit: MAX_UPLOAD_CHUNK_BYTES }), route(async (req, res) => { const account = await requestAccount(req); const result = await assetService.appendUpload(account.id, req.params.projectId, req.params.uploadId, { buffer: req.body, offset: Number(req.get("x-upload-offset")), total: Number(req.get("x-upload-total")), mimeType: req.get("x-upload-mime"), originalName: req.get("x-file-name") }); res.status(202).json({ ok: true, upload: result }); }));
  router.post("/projects/:projectId/uploads/:uploadId/finalize", route(async (req, res) => { const account = await requestAccount(req); res.status(201).json({ ok: true, asset: await assetService.finalizeUpload(account.id, req.params.projectId, req.params.uploadId) }); }));
  router.post("/projects/:projectId/assets", express.raw({ type: () => true, limit: MAX_ASSET_BYTES }), route(async (req, res) => { const account = await requestAccount(req); const asset = await assetService.importBuffer(account.id, req.params.projectId, { buffer: req.body, mimeType: req.get("content-type"), originalName: req.get("x-file-name") || "asset" }); res.status(201).json({ ok: true, asset }); }));
  router.get("/projects/:projectId/assets/:assetId", route(async (req, res) => { const account = await requestAccount(req); res.json({ ok: true, asset: assetService.get(account.id, req.params.projectId, req.params.assetId) }); }));
  router.get("/projects/:projectId/assets/:assetId/content", route(async (req, res) => { const account = await requestAccount(req); const { asset, filePath } = assetService.contentPath(account.id, req.params.projectId, req.params.assetId); res.type(asset.mimeType); res.setHeader("Content-Disposition", `inline; filename="${asset.originalName.replace(/["\\]/g, "_")}"`); res.sendFile(filePath); }));
  router.get("/projects/:projectId/assets/:assetId/proxy-content", route(async (req, res) => { const account = await requestAccount(req); const proxy = assetService.latestDerivative(account.id, req.params.projectId, req.params.assetId, "proxy"); const { asset, filePath } = assetService.contentPath(account.id, req.params.projectId, proxy.id); res.type(asset.mimeType); res.setHeader("Content-Disposition", `inline; filename="${asset.originalName.replace(/["\\]/g, "_")}"`); res.sendFile(filePath); }));
  router.delete("/projects/:projectId/assets/:assetId", route(async (req, res) => { const account = await requestAccount(req); res.json({ ok: true, asset: assetService.delete(account.id, req.params.projectId, req.params.assetId) }); }));

  router.get("/projects/:projectId/renders", route(async (req, res) => { const account = await requestAccount(req); res.json({ ok: true, renders: renderService.list(account.id, req.params.projectId) }); }));
  router.post("/projects/:projectId/renders", route(async (req, res) => { const account = await requestAccount(req); res.status(201).json({ ok: true, render: renderService.create(account.id, req.params.projectId, req.body || {}) }); }));
  router.get("/projects/:projectId/renders/:renderId", route(async (req, res) => { const account = await requestAccount(req); res.json({ ok: true, render: renderService.get(account.id, req.params.projectId, req.params.renderId) }); }));
  router.post("/projects/:projectId/renders/:renderId/process", route(async (req, res) => { const account = await requestAccount(req); res.json({ ok: true, render: await renderService.process(account.id, req.params.projectId, req.params.renderId) }); }));
  router.post("/projects/:projectId/renders/:renderId/cancel", route(async (req, res) => { const account = await requestAccount(req); res.json({ ok: true, render: renderService.cancel(account.id, req.params.projectId, req.params.renderId) }); }));
  router.post("/projects/:projectId/renders/:renderId/retry", route(async (req, res) => { const account = await requestAccount(req); res.json({ ok: true, render: renderService.retry(account.id, req.params.projectId, req.params.renderId) }); }));
  router.get("/projects/:projectId/renders/:renderId/content", route(async (req, res) => { const account = await requestAccount(req); res.type("video/mp4").sendFile(renderService.content(account.id, req.params.projectId, req.params.renderId).filePath); }));

  router.get("/projects/:projectId/publications", route(async (req, res) => { const account = await requestAccount(req); res.json({ ok: true, publications: publicationService.list(account.id, req.params.projectId) }); }));
  router.post("/projects/:projectId/publications", route(async (req, res) => { const account = await requestAccount(req); res.status(201).json({ ok: true, publication: await publicationService.create(account.id, req.params.projectId, req.body || {}) }); }));
  router.post("/projects/:projectId/publications/:publicationId/cancel", route(async (req, res) => { const account = await requestAccount(req); res.json({ ok: true, publication: await publicationService.cancel(account.id, req.params.projectId, req.params.publicationId) }); }));
  router.post("/projects/:projectId/publications/:publicationId/retry", route(async (req, res) => { const account = await requestAccount(req); res.json({ ok: true, publication: await publicationService.retry(account.id, req.params.projectId, req.params.publicationId) }); }));
  router.post("/projects/:projectId/publications/:publicationId/confirm", route(async (req, res) => { const account = await requestAccount(req); res.json({ ok: true, publication: publicationService.confirm(account.id, req.params.projectId, req.params.publicationId, req.body || {}) }); }));

  router.get("/events", route(async (req, res) => { const account = await requestAccount(req); res.status(200); res.setHeader("Content-Type", "text/event-stream"); res.setHeader("Cache-Control", "no-cache, no-store"); res.setHeader("Connection", "keep-alive"); res.flushHeaders?.(); const unsubscribe = eventHub.subscribe(account.id, res); req.on("close", unsubscribe); }));
  router.use((error, req, res, next) => { if (res.headersSent) return next(error); const tooLarge = error?.type === "entity.too.large"; const statusCode = tooLarge ? 413 : Number(error.statusCode) || 500; if (statusCode >= 500) console.error(error); res.status(statusCode).json({ ok: false, error: error.message || "Studio request failed.", code: error.code || (tooLarge ? "asset_too_large" : "studio_error") }); });
  return router;
}
module.exports = { createStudioRouter };
