/**
 * Cookies por cuenta para AutoClone.
 *
 * Uso: copia este archivo a la raiz del proyecto (donde esta package.json)
 * y ejecuta:   node instalar-cookies.js
 *
 * Que hace:
 *  1. Al cerrar la ventana de login de TikTok, vuelca las cookies de ESA cuenta
 *     a .runtime/cookies/<cuenta>.txt en formato Netscape (lo que lee yt-dlp).
 *     Playwright las entrega el mismo, asi que no hay que descifrar nada.
 *  2. AutoClone usa el archivo de la cuenta activa en sus llamadas a yt-dlp.
 *  3. Si no hay cookies, sigue descargando como antes (nunca empeora).
 *
 * Se puede ejecutar dos veces sin duplicar. Si algo no encaja, se detiene.
 */
const fs = require("fs");
const path = require("path");

const ROOT = __dirname;

let added = 0;
let present = 0;
const failures = [];

function read(rel) {
  const file = path.join(ROOT, rel);
  if (!fs.existsSync(file)) {
    console.error(`\n  ERROR: falta ${rel}`);
    console.error("  Copia este archivo a la raiz del proyecto (donde esta package.json) y vuelve a ejecutarlo.\n");
    process.exit(1);
  }
  return fs.readFileSync(file, "utf8");
}

function write(rel, text) {
  fs.writeFileSync(path.join(ROOT, rel), text, "utf8");
}

function patch(rel, id, label, from, to) {
  const idMark = `CK[${id}]`;
  let text = read(rel);
  if (text.includes(idMark)) {
    console.log(`  ya estaba  ${label}`);
    present += 1;
    return;
  }
  const index = text.indexOf(from);
  if (index === -1) {
    console.error(`  FALLO      ${label}  (${rel})`);
    failures.push(`${label} -> ${rel}`);
    return;
  }
  text = text.slice(0, index) + to + ` // ${idMark}` + text.slice(index + from.length);
  write(rel, text);
  added += 1;
  console.log(`  aplicado   ${label}`);
}

console.log("\nInstalando cookies por cuenta para AutoClone...\n");

// ---------------------------------------------------------------- 1) modulo nuevo
const cookieJarPath = path.join(ROOT, "src", "cookie-jar.js");
if (fs.existsSync(cookieJarPath)) {
  console.log("  ya estaba  src/cookie-jar.js");
  present += 1;
} else {
  fs.writeFileSync(cookieJarPath, `/**
 * Per-account cookie files for yt-dlp.
 *
 * The app logs in through its own persistent Chromium profile, but yt-dlp is a
 * separate program and Windows encrypts that profile's cookie DB (DPAPI), so
 * yt-dlp can never read it. Instead, Playwright hands us the cookies of the
 * context it owns (no decryption needed) and we write them to a Netscape
 * cookies.txt per account, which is exactly the format yt-dlp reads.
 *
 * Files live in .runtime/cookies/<accountId>.txt and are gitignored.
 */
const fs = require("fs/promises");
const path = require("path");
const { config } = require("./config");

const COOKIES_DIR = path.resolve(config.projectRoot, ".runtime", "cookies");

function safeAccountId(accountId) {
  return String(accountId || "").replace(/[^a-zA-Z0-9._-]/g, "").slice(0, 60) || "default";
}

function cookieFilePath(accountId) {
  return path.join(COOKIES_DIR, \`\${safeAccountId(accountId)}.txt\`);
}

/** Netscape cookies.txt cannot represent these, and yt-dlp ignores them. */
function isEncodeable(cookie) {
  if (!cookie || !cookie.name) return false;
  if (/[\\t\\r\\n]/.test(cookie.name) || /[\\t\\r\\n]/.test(cookie.value || "")) return false;
  return true;
}

function toNetscape(cookies) {
  const lines = [
    "# Netscape HTTP Cookie File",
    "# Generated by AutoSocial Studio. Do not edit by hand.",
    "",
  ];
  for (const cookie of cookies || []) {
    if (!isEncodeable(cookie)) continue;
    let domain = String(cookie.domain || "");
    if (!domain) continue;
    // yt-dlp expects a leading dot for wildcard/subdomain cookies, and the
    // second column must agree with it.
    const includeSubdomains = domain.startsWith(".") ? "TRUE" : "FALSE";
    const expires = Number.isFinite(cookie.expires) && cookie.expires > 0
      ? Math.floor(cookie.expires)
      : 0;
    lines.push([
      domain,
      includeSubdomains,
      cookie.path || "/",
      cookie.secure ? "TRUE" : "FALSE",
      String(expires),
      cookie.name,
      cookie.value || "",
    ].join("\\t"));
  }
  return lines.join("\\n") + "\\n";
}

/**
 * Write the cookies of a live Playwright context for one account.
 * Returns { ok, path, count } or { ok:false, error }.
 */
async function saveCookiesFromContext(context, accountId) {
  try {
    if (!context || typeof context.cookies !== "function") {
      return { ok: false, error: "El contexto del navegador no esta disponible." };
    }
    const cookies = await context.cookies();
    if (!cookies.length) {
      return { ok: false, error: "El navegador no devolvio cookies." };
    }
    await fs.mkdir(COOKIES_DIR, { recursive: true });
    const target = cookieFilePath(accountId);
    const tmp = \`\${target}.tmp-\${process.pid}-\${Date.now()}\`;
    await fs.writeFile(tmp, toNetscape(cookies), "utf8");
    await fs.rename(tmp, target);
    // Only the current OS user should read live session cookies.
    await fs.chmod(target, 0o600).catch(() => { });
    return { ok: true, path: target, count: cookies.filter(isEncodeable).length };
  } catch (error) {
    return { ok: false, error: error.message };
  }
}

/** Path to the saved cookie file for an account, or "" when it does not exist. */
async function cookieFileForAccount(accountId) {
  const target = cookieFilePath(accountId);
  try {
    const stat = await fs.stat(target);
    if (stat.isFile() && stat.size > 0) return target;
  } catch { /* not saved yet */ }
  return "";
}

/** yt-dlp argument pair for an account, or [] when there are no cookies. */
async function cookieArgsForAccount(accountId) {
  const file = await cookieFileForAccount(accountId);
  return file ? ["--cookies", file] : [];
}

async function deleteCookiesForAccount(accountId) {
  await fs.rm(cookieFilePath(accountId), { force: true });
}

module.exports = {
  COOKIES_DIR,
  cookieFilePath,
  cookieFileForAccount,
  cookieArgsForAccount,
  saveCookiesFromContext,
  deleteCookiesForAccount,
  toNetscape,
};
`, "utf8");
  added += 1;
  console.log("  creado     src/cookie-jar.js");
}

// ---------------------------------------------------------------- 2) volcar al cerrar login
patch(
  "src/tiktok-uploader.js",
  "dump",
  "login: volcar cookies al cerrar",
  `async function closeCurrentLoginContext() {
  if (!loginSessionContext) return false;
  const context = loginSessionContext;
  loginSessionContext = null;
  loginSessionAccountId = null;
  tempMailSetupPage = null;
  tempMailCaptureHandler = null;
  await context.close().catch(() => { });
  return true;
}`,
  `async function closeCurrentLoginContext() {
  if (!loginSessionContext) return false;
  const context = loginSessionContext;
  const accountId = loginSessionAccountId;
  // Save the session cookies for yt-dlp BEFORE closing: Playwright hands them
  // to us directly, so no DPAPI decryption is involved. Best effort only.
  if (accountId) {
    try {
      const jar = require("./cookie-jar");
      const saved = await jar.saveCookiesFromContext(context, accountId);
      if (saved.ok) {
        console.log(\`Saved \${saved.count} cookies for account \${accountId}.\`);
      } else {
        console.log(\`Could not save cookies for \${accountId}: \${saved.error}\`);
      }
    } catch (error) {
      console.log(\`Could not save cookies for \${accountId}: \${error.message}\`);
    }
  }
  loginSessionContext = null;
  loginSessionAccountId = null;
  tempMailSetupPage = null;
  tempMailCaptureHandler = null;
  await context.close().catch(() => { });
  return true;
}`,
);

// ---------------------------------------------------------------- 3) AutoClone usa las cookies
patch(
  "src/autoclone/controller.js",
  "read",
  "autoclone: leer cookies de la cuenta",
  `  /** Read the Gemini key saved by the Competencia section so both share it. */
  async _aiSettings() {`,
  `  /** Cookie flags for the active account, so yt-dlp can use the saved session. */
  async _cookieArgs() {
    try {
      const { getActiveAccount } = require("../account-manager");
      const jar = require("../cookie-jar");
      const account = await getActiveAccount();
      return await jar.cookieArgsForAccount(account && account.id ? account.id : "default");
    } catch {
      return [];
    }
  }

  /** Read the Gemini key saved by the Competencia section so both share it. */
  async _aiSettings() {`,
);

// single-video download (:525)
patch(
  "src/autoclone/controller.js",
  "single",
  "autoclone: cookies en descarga de video suelto",
  `        const downloadArgs = [
          "--no-warnings", "-f", "mp4/bestvideo*+bestaudio/best",
          "--merge-output-format", "mp4", "-o", target,
          "--write-info-json",
        ];
        if (job.options.downloadThumbnail) downloadArgs.push("--write-thumbnail");
        downloadArgs.push(job.videoUrl);`,
  `        const cookieArgs = await this._cookieArgs();
        const downloadArgs = [
          "--no-warnings", ...cookieArgs, "-f", "mp4/bestvideo*+bestaudio/best",
          "--merge-output-format", "mp4", "-o", target,
          "--write-info-json",
        ];
        if (job.options.downloadThumbnail) downloadArgs.push("--write-thumbnail");
        downloadArgs.push(job.videoUrl);`,
);

// profile listing (:563)
patch(
  "src/autoclone/controller.js",
  "list",
  "autoclone: cookies al listar el perfil",
  `    const listArgs = ["--no-warnings", "--flat-playlist", "--print", "%(id)s"];`,
  `    const cookieArgs = await this._cookieArgs();
    const listArgs = ["--no-warnings", ...cookieArgs, "--flat-playlist", "--print", "%(id)s"];`,
);

// profile per-video download (:593)
patch(
  "src/autoclone/controller.js",
  "loop",
  "autoclone: cookies en descarga del perfil",
  `        const downloadArgs = [
          "--no-warnings", "-f", "mp4/bestvideo*+bestaudio/best",
          "--merge-output-format", "mp4", "-o", target,
          "--write-info-json",
        ];
        if (job.options.downloadThumbnail) downloadArgs.push("--write-thumbnail");
        downloadArgs.push(\`https://www.tiktok.com/\${job.handle}/video/\${id}\`);`,
  `        const downloadArgs = [
          "--no-warnings", ...cookieArgs, "-f", "mp4/bestvideo*+bestaudio/best",
          "--merge-output-format", "mp4", "-o", target,
          "--write-info-json",
        ];
        if (job.options.downloadThumbnail) downloadArgs.push("--write-thumbnail");
        downloadArgs.push(\`https://www.tiktok.com/\${job.handle}/video/\${id}\`);`,
);

// ---------------------------------------------------------------- resultado
if (failures.length) {
  console.error(`\n  ${failures.length} cambio(s) NO se pudieron aplicar:`);
  for (const f of failures) console.error(`    - ${f}`);
  console.error("\n  Tu version de esos archivos es distinta a la esperada.");
  console.error("  Pasa este mensaje completo y lo ajusto.\n");
  process.exit(1);
}

// ---------------------------------------------------------------- .gitignore
try {
  const ignorePath = path.join(ROOT, ".gitignore");
  if (fs.existsSync(ignorePath)) {
    let ignore = fs.readFileSync(ignorePath, "utf8");
    if (!ignore.includes(".runtime/cookies")) {
      ignore += "\n# Per-account cookies exported for yt-dlp (live sessions)\n.runtime/cookies/\n";
      fs.writeFileSync(ignorePath, ignore, "utf8");
      console.log("  aplicado   .gitignore: ignorar .runtime/cookies/");
      added += 1;
    } else {
      console.log("  ya estaba  .gitignore");
      present += 1;
    }
  }
} catch { /* non-fatal */ }

console.log(`\nListo. ${added} cambios aplicados, ${present} ya estaban.\n`);
console.log("Como funciona:");
console.log("  1. Abre el dashboard -> Accounts -> inicia sesion de TikTok de esa cuenta.");
console.log("  2. Cuando CIERRES la ventana de Chromium, las cookies se guardan solas");
console.log("     en .runtime/cookies/<cuenta>.txt");
console.log("  3. AutoClone usara ese archivo al descargar con esa cuenta activa.\n");
console.log("Importante: cierra la ventana de login para que se guarden las cookies.\n");
