import type { AudioMix, AudioRole, BibleContent, BibleEntity, BriefContent, ClipTransform, ColorGrade, GraphContent, GraphNode, ScriptAct, ScriptContent, ScriptScene, StoryboardContent, StoryboardShot, SubtitleCue, SubtitleStyle, TimelineClip, TimelineContent, TimelineTrack } from "./types";

export const uid = (prefix: string) => `${prefix}-${Date.now().toString(36)}-${Math.random().toString(36).slice(2, 7)}`;
const text = (value: unknown, fallback = "") => typeof value === "string" ? value : fallback;
const number = (value: unknown, fallback: number) => typeof value === "number" && Number.isFinite(value) ? value : fallback;
const object = (value: unknown): Record<string, unknown> => value && typeof value === "object" && !Array.isArray(value) ? value as Record<string, unknown> : {};
const array = (value: unknown): unknown[] => Array.isArray(value) ? value : [];
export const clamp = (value: number, min: number, max: number) => Math.min(max, Math.max(min, Math.round(value)));

export function defaultBrief(seed?: Partial<BriefContent>): BriefContent { return { title: text(seed?.title), audience: text(seed?.audience), objective: text(seed?.objective), format: text(seed?.format), tone: text(seed?.tone), themes: text(seed?.themes), constraints: text(seed?.constraints), successCriteria: text(seed?.successCriteria) }; }
function block(raw: unknown) { const x = object(raw); const type = ["action", "dialogue", "voiceover", "transition"].includes(text(x.type)) ? text(x.type) as "action" | "dialogue" | "voiceover" | "transition" : "action"; return { id: text(x.id, uid("block")), type, speaker: text(x.speaker), text: text(x.text) }; }
function scene(raw: unknown): ScriptScene { const x = object(raw); return { id: text(x.id, uid("scene")), heading: text(x.heading, "New scene"), location: text(x.location), timeOfDay: text(x.timeOfDay), summary: text(x.summary), blocks: array(x.blocks).map(block) }; }
function act(raw: unknown): ScriptAct { const x = object(raw); return { id: text(x.id, uid("act")), title: text(x.title, "Act"), purpose: text(x.purpose), scenes: array(x.scenes).map(scene) }; }
export function normalizeScript(raw: unknown): ScriptContent { const x = object(raw); return { logline: text(x.logline), synopsis: text(x.synopsis), acts: array(x.acts).map(act) }; }
export function localOutline(prompt: string): ScriptContent { const premise = prompt.trim() || "An unresolved idea becomes a clear story."; const purposes = ["Establish the world, desire, and inciting incident.", "Escalate obstacles and force a decisive choice.", "Resolve the central question and show the change."]; return { logline: premise.split(/\n|\./)[0].slice(0, 180), synopsis: premise, acts: purposes.map((purpose, i) => ({ id: uid("act"), title: `Act ${i + 1}`, purpose, scenes: [{ id: uid("scene"), heading: i === 0 ? "OPENING" : i === 1 ? "TURNING POINT" : "RESOLUTION", location: "TBD", timeOfDay: "DAY", summary: purpose, blocks: [{ id: uid("block"), type: "action", speaker: "", text: purpose }] }] })) }; }
function entity(raw: unknown): BibleEntity { const x = object(raw); return { id: text(x.id, uid("entity")), name: text(x.name, "Untitled"), description: text(x.description), continuity: text(x.continuity), canonicalPrompt: text(x.canonicalPrompt), negativePrompt: text(x.negativePrompt), assetIds: array(x.assetIds).map(String), locked: Boolean(x.locked), approved: Boolean(x.approved) }; }
export function normalizeBible(raw: unknown): BibleContent { const x = object(raw); return { style: text(x.style), continuity: text(x.continuity), canonicalPrompt: text(x.canonicalPrompt), negativePrompt: text(x.negativePrompt), palette: array(x.palette).map(String), locked: Boolean(x.locked), approved: Boolean(x.approved), characters: array(x.characters).map(entity), locations: array(x.locations).map(entity), wardrobe: array(x.wardrobe).map(entity), props: array(x.props).map(entity) }; }
export function normalizeStoryboard(raw: unknown): StoryboardContent { const x = object(raw); return { roughCutApproved: Boolean(x.roughCutApproved), shots: array(x.shots).map((rawShot): StoryboardShot => { const s = object(rawShot); const status = ["draft", "ready", "approved", "generating", "failed"].includes(text(s.status)) ? text(s.status) as StoryboardShot["status"] : "draft"; return { id: text(s.id, uid("shot")), sceneId: text(s.sceneId), title: text(s.title, "Shot"), durationMs: clamp(number(s.durationMs, 3000), 100, 3_600_000), camera: text(s.camera), framing: text(s.framing), lens: text(s.lens), movement: text(s.movement), action: text(s.action), dialogue: text(s.dialogue), prompt: text(s.prompt), referenceAssetIds: array(s.referenceAssetIds).map(String), generatedAssetId: text(s.generatedAssetId) || undefined, status }; }) }; }
export function shotsFromScript(script: ScriptContent): StoryboardShot[] { return script.acts.flatMap((a) => a.scenes.map((s, i) => ({ id: uid("shot"), sceneId: s.id, title: `${s.heading} - ${i + 1}`, durationMs: 5000, camera: "Eye level", framing: "Medium", lens: "50mm", movement: "Locked", action: s.summary, dialogue: s.blocks.filter((b) => b.type === "dialogue").map((b) => `${b.speaker}: ${b.text}`).join("\n"), prompt: [s.location, s.timeOfDay, s.summary].filter(Boolean).join(", "), referenceAssetIds: [], status: "draft" as const }))); }

export const defaultTransform = (): ClipTransform => ({ opacity: 100, x: 0, y: 0, scale: 100, rotation: 0, keyframes: {} });
export const defaultGrade = (): ColorGrade => ({ exposure: 0, contrast: 0, gamma: 1, highlights: 0, shadows: 0, saturation: 100, temperature: 0, tint: 0, vignette: 0, keyframes: {} });
export const defaultMix = (): AudioMix => ({ gainDb: 0, pan: 0, muted: false, solo: false, fadeInMs: 0, fadeOutMs: 0, ducking: 0, normalization: "none", role: "dialogue" });
export const defaultSubtitleStyle = (): SubtitleStyle => ({ fontFamily: "sans-serif", fontSize: 42, textColor: "#ffffff", backgroundColor: "#000000", position: "bottom", animation: "none" });
function clip(raw: unknown, trackId: string): TimelineClip {
  const x = object(raw);
  const editor = object(x.editor);
  const transform = { ...defaultTransform(), ...object(x.transform), ...object(editor.transform) } as ClipTransform;
  const grade = { ...defaultGrade(), ...object(x.color), ...object(x.grade), ...object(editor.grade) } as ColorGrade;
  transform.keyframes = object(transform.keyframes) as ClipTransform["keyframes"];
  grade.keyframes = object(grade.keyframes) as ColorGrade["keyframes"];
  const existingKeyframeProperties = new Set([...Object.keys(transform.keyframes), ...Object.keys(grade.keyframes)]);
  for (const rawFrame of array(x.keyframes)) { const frame = object(rawFrame), property = text(frame.property), easingValue = text(frame.easing); const target = property in defaultTransform() ? transform.keyframes : property in defaultGrade() ? grade.keyframes : null; if (!target || existingKeyframeProperties.has(property) || typeof frame.value !== "number") continue; const easing = ["linear", "ease-in", "ease-out", "ease-in-out"].includes(easingValue) ? easingValue as "linear" | "ease-in" | "ease-out" | "ease-in-out" : "linear"; target[property] = [...(target[property] || []), { id: text(frame.id, uid("kf")), timeMs: number(frame.timeMs, 0), value: frame.value, easing }]; }
  const renderedAudio = object(x.audio);
  const renderedGainDb = typeof renderedAudio.volume === "number" && renderedAudio.volume > 0 ? 20 * Math.log10(renderedAudio.volume) : 0;
  const editorAudio = object(editor.audio);
  const roleValue = text(editorAudio.role, text(renderedAudio.role));
  const role: AudioRole = ["dialogue", "voiceover", "music", "sfx"].includes(roleValue) ? roleValue as AudioRole : "dialogue";
  const normalizationValue = text(editorAudio.normalization, text(renderedAudio.normalization));
  const normalization: AudioMix["normalization"] = ["none", "peak", "loudness"].includes(normalizationValue) ? normalizationValue as AudioMix["normalization"] : "none";
  const audio = { ...defaultMix(), gainDb: renderedGainDb, pan: number(renderedAudio.pan, 0), fadeInMs: number(renderedAudio.fadeInMs, 0), fadeOutMs: number(renderedAudio.fadeOutMs, 0), ducking: number(renderedAudio.ducking, 0), ...editorAudio, role, normalization } as AudioMix;
  const kind = ["image", "video", "audio", "subtitle", "lut", "other"].includes(text(x.kind)) ? text(x.kind) as TimelineClip["kind"] : "other";
  return { id: text(x.id, uid("clip")), trackId, assetId: text(x.assetId) || undefined, name: text(x.name, "Clip"), kind, startMs: Math.max(0, number(x.startMs, 0)), durationMs: Math.max(1, number(x.durationMs, 3000)), sourceStartMs: Math.max(0, number(x.sourceStartMs, number(x.trimStartMs, 0))), transform, grade, audio };
}
function track(raw: unknown): TimelineTrack { const x = object(raw); const id = text(x.id, uid("track")); const kindValue = text(x.kind, text(x.type)); const kind = ["video", "audio", "subtitle"].includes(kindValue) ? kindValue as TimelineTrack["kind"] : "video"; return { id, name: text(x.name, kind.toUpperCase()), kind, muted: Boolean(x.muted), solo: Boolean(x.solo), locked: Boolean(x.locked), clips: array(x.clips).map((c) => clip(c, id)) }; }
export function normalizeTimeline(raw: unknown): TimelineContent { const x = object(raw); const tracks = array(x.tracks).map(track); const rawStyle = object(x.subtitleStyle); const positionValue = text(rawStyle.position); const animationValue = text(rawStyle.animation); const subtitleStyle: SubtitleStyle = { ...defaultSubtitleStyle(), fontFamily: text(rawStyle.fontFamily, "sans-serif"), fontSize: Math.max(8, number(rawStyle.fontSize, 42)), textColor: text(rawStyle.textColor, "#ffffff"), backgroundColor: text(rawStyle.backgroundColor, "#000000"), position: ["top", "center", "bottom"].includes(positionValue) ? positionValue as SubtitleStyle["position"] : "bottom", animation: ["none", "fade", "pop", "karaoke"].includes(animationValue) ? animationValue as SubtitleStyle["animation"] : "none" }; return { durationMs: Math.max(1000, number(x.durationMs, 60_000)), tracks: tracks.length ? tracks : [{ id: uid("video"), name: "V1", kind: "video", muted: false, solo: false, locked: false, clips: [] }, { id: uid("audio"), name: "A1", kind: "audio", muted: false, solo: false, locked: false, clips: [] }], subtitles: array(x.subtitles).map((r): SubtitleCue => { const c = object(r); return { id: text(c.id, uid("cue")), startMs: number(c.startMs, 0), endMs: number(c.endMs, 2000), text: text(c.text) }; }), subtitleStyle, lutAssetId: text(x.lutAssetId) || undefined }; }

const defaultGraphNodes = (): GraphNode[] => [
  ["brief", "Brief", "document", 40, 120, "Story"], ["script", "Script", "document", 200, 120, "Story"], ["bible", "Visual Bible", "document", 360, 40, "References"], ["references", "References", "document", 360, 200, "References"], ["storyboard", "Storyboard", "document", 520, 120, "Storyboard"], ["timeline", "Edit Timeline", "document", 680, 120, "Edit"], ["deliver", "Delivery", "action", 840, 120, "Deliver"]
].map(([id, label, type, x, y, workspace]) => ({ id: String(id), label: String(label), type: String(type), x: Number(x), y: Number(y), workspace: String(workspace), config: {} }));
export function defaultGraph(): GraphContent { const nodes = defaultGraphNodes(); return { nodes, edges: nodes.slice(0, -1).map((node, index) => ({ id: `edge-${node.id}-${nodes[index + 1].id}`, from: node.id, to: nodes[index + 1].id })), settings: { autoRun: false } }; }
export function normalizeGraph(raw: unknown): GraphContent { const x = object(raw); const nodes = array(x.nodes).map((value): GraphNode => { const node = object(value); return { id: text(node.id, uid("node")), label: text(node.label, "Node"), type: text(node.type, "document"), x: number(node.x, 40), y: number(node.y, 40), workspace: text(node.workspace, "Story"), config: object(node.config) }; }); const ids = new Set(nodes.map((node) => node.id)); const seen = new Set<string>(); const edges = array(x.edges).flatMap((value) => { const edge = object(value), from = text(edge.from), to = text(edge.to), pair = `${from}\u0000${to}`; if (!ids.has(from) || !ids.has(to) || from === to || seen.has(pair)) return []; seen.add(pair); return [{ id: text(edge.id, uid("edge")), from, to }]; }); return nodes.length ? { nodes, edges, settings: { autoRun: Boolean(object(x.settings).autoRun) } } : defaultGraph(); }
export function graphEdgeError(graph: GraphContent, from: string, to: string): string | null { if (!from || !to) return "Choose both nodes."; if (from === to) return "A node cannot depend on itself."; if (graph.edges.some((edge) => edge.from === from && edge.to === to)) return "That edge already exists."; const adjacency = new Map<string, string[]>(); for (const edge of graph.edges) adjacency.set(edge.from, [...(adjacency.get(edge.from) || []), edge.to]); adjacency.set(from, [...(adjacency.get(from) || []), to]); const visit = (id: string, active: Set<string>, done: Set<string>): boolean => { if (active.has(id)) return true; if (done.has(id)) return false; active.add(id); for (const next of adjacency.get(id) || []) if (visit(next, active, done)) return true; active.delete(id); done.add(id); return false; }; return graph.nodes.some((node) => visit(node.id, new Set(), new Set())) ? "That edge would create a cycle." : null; }
export function snap(value: number, points: number[], threshold = 120): number { const nearest = points.reduce((a, b) => Math.abs(b - value) < Math.abs(a - value) ? b : a, value); return Math.abs(nearest - value) <= threshold ? nearest : Math.max(0, Math.round(value)); }
export function timecode(ms: number) { const total = Math.max(0, Math.round(ms)); const h = Math.floor(total / 3_600_000), m = Math.floor(total / 60_000) % 60, s = Math.floor(total / 1000) % 60, milli = total % 1000; return `${String(h).padStart(2, "0")}:${String(m).padStart(2, "0")}:${String(s).padStart(2, "0")}.${String(milli).padStart(3, "0")}`; }
export function parseSubtitles(input: string): SubtitleCue[] { const normalized = input.replace(/\r/g, "").replace(/WEBVTT[^\n]*\n/, ""); return normalized.split(/\n\s*\n/).flatMap((part) => { const lines = part.trim().split("\n"); const timingIndex = lines.findIndex((l) => l.includes("-->")); if (timingIndex < 0) return []; const parse = (v: string) => { const pieces = v.trim().replace(",", ".").split(":").map(Number); return Math.round(((pieces.at(-3) || 0) * 3600 + (pieces.at(-2) || 0) * 60 + (pieces.at(-1) || 0)) * 1000); }; const [a, b] = lines[timingIndex].split("-->"); return [{ id: uid("cue"), startMs: parse(a), endMs: parse(b), text: lines.slice(timingIndex + 1).join("\n") }]; }); }
export function exportSubtitles(cues: SubtitleCue[], vtt: boolean) { return `${vtt ? "WEBVTT\n\n" : ""}${cues.map((c, i) => `${vtt ? "" : `${i + 1}\n`}${timecode(c.startMs).replace(vtt ? /,/g : /\./g, vtt ? "." : ",")} --> ${timecode(c.endMs).replace(vtt ? /,/g : /\./g, vtt ? "." : ",")}\n${c.text}`).join("\n\n")}\n`; }
