/**
 * Per-account cookie files for yt-dlp.
 *
 * The app logs in through its own persistent Chromium profile, but yt-dlp is a
 * separate program and Windows encrypts that profile's cookie DB (DPAPI), so
 * yt-dlp can never read it. Instead, Playwright hands us the cookies of the
 * context it owns (no decryption needed) and we write them to a Netscape
 * cookies.txt per account, which is exactly the format yt-dlp reads.
 *
 * Files live in .runtime/cookies/<accountId>.txt and are gitignored.
 */
const fs = require("fs/promises");
const path = require("path");
const { config } = require("./config");

const COOKIES_DIR = path.resolve(config.projectRoot, ".runtime", "cookies");

function safeAccountId(accountId) {
  return String(accountId || "").replace(/[^a-zA-Z0-9._-]/g, "").slice(0, 60) || "default";
}

function cookieFilePath(accountId) {
  return path.join(COOKIES_DIR, `${safeAccountId(accountId)}.txt`);
}

/** Netscape cookies.txt cannot represent these, and yt-dlp ignores them. */
function isEncodeable(cookie) {
  if (!cookie || !cookie.name) return false;
  if (/[\t\r\n]/.test(cookie.name) || /[\t\r\n]/.test(cookie.value || "")) return false;
  return true;
}

function toNetscape(cookies) {
  const lines = [
    "# Netscape HTTP Cookie File",
    "# Generated by AutoSocial Studio. Do not edit by hand.",
    "",
  ];
  for (const cookie of cookies || []) {
    if (!isEncodeable(cookie)) continue;
    let domain = String(cookie.domain || "");
    if (!domain) continue;
    // yt-dlp expects a leading dot for wildcard/subdomain cookies, and the
    // second column must agree with it.
    const includeSubdomains = domain.startsWith(".") ? "TRUE" : "FALSE";
    const expires = Number.isFinite(cookie.expires) && cookie.expires > 0
      ? Math.floor(cookie.expires)
      : 0;
    lines.push([
      domain,
      includeSubdomains,
      cookie.path || "/",
      cookie.secure ? "TRUE" : "FALSE",
      String(expires),
      cookie.name,
      cookie.value || "",
    ].join("\t"));
  }
  return lines.join("\n") + "\n";
}

/**
 * Write the cookies of a live Playwright context for one account.
 * Returns { ok, path, count } or { ok:false, error }.
 */
async function saveCookiesFromContext(context, accountId) {
  try {
    if (!context || typeof context.cookies !== "function") {
      return { ok: false, error: "El contexto del navegador no esta disponible." };
    }
    const cookies = await context.cookies();
    if (!cookies.length) {
      return { ok: false, error: "El navegador no devolvio cookies." };
    }
    await fs.mkdir(COOKIES_DIR, { recursive: true });
    const target = cookieFilePath(accountId);
    const tmp = `${target}.tmp-${process.pid}-${Date.now()}`;
    await fs.writeFile(tmp, toNetscape(cookies), "utf8");
    await fs.rename(tmp, target);
    // Only the current OS user should read live session cookies.
    await fs.chmod(target, 0o600).catch(() => { });
    return { ok: true, path: target, count: cookies.filter(isEncodeable).length };
  } catch (error) {
    return { ok: false, error: error.message };
  }
}

/** Path to the saved cookie file for an account, or "" when it does not exist. */
async function cookieFileForAccount(accountId) {
  const target = cookieFilePath(accountId);
  try {
    const stat = await fs.stat(target);
    if (stat.isFile() && stat.size > 0) return target;
  } catch { /* not saved yet */ }
  return "";
}

/** yt-dlp argument pair for an account, or [] when there are no cookies. */
async function cookieArgsForAccount(accountId) {
  const file = await cookieFileForAccount(accountId);
  return file ? ["--cookies", file] : [];
}

async function deleteCookiesForAccount(accountId) {
  await fs.rm(cookieFilePath(accountId), { force: true });
}

module.exports = {
  COOKIES_DIR,
  cookieFilePath,
  cookieFileForAccount,
  cookieArgsForAccount,
  saveCookiesFromContext,
  deleteCookiesForAccount,
  toNetscape,
};
